### ISSUE TITLE
make embed examples for all "standard sizes"

### ISSUE THREAD

**Issue by jellegerbrandy** [Paratii-Video/paratii-embed#1]
i.e. lets have a page for each of the sizes in this issue: https://github.com/Paratii-Video/paratii-player/issues/116

I.e. have a pages similar to
https://paratii-video.github.io/paratii-embed/simpleembed.html

but then at URLS like `embed-tiny.html`, `embed-large.html` etc. 

also put some lorem ipsum text around it, to get a better idea.

**Comment by geckoslair** [comment]
https://paratii-video.github.io/paratii-embed/embedding.html
